export const AI_MODELS = {
  grok: { provider: "Grok", apiModel: "grok-4.20-reasoning" },
} as const;

export type AiModelKey = keyof typeof AI_MODELS;

export interface StockSnapshot {
  ticker: string;
  shares: number;
  totalCost: number;
  currentPrice: number;
  changePercent: number;
  currentValue: number;
}

const LANGUAGE_INSTRUCTIONS = {
  en: "Write your entire response in English.",
  es: "Escribe toda tu respuesta en español.",
};

export function normalizeMarkdownOutput(text: string): string {
  let normalized = text.trim();
  normalized = normalized.replace(/\s*\(gpt-4o-mini\)\s*\[OpenAI\]\s*$/i, "");
  normalized = normalized.replace(/\s*\[(Grok|OpenAI)\]\s*$/i, "");
  normalized = normalized.replace(/([^\n])\s+(#{1,6}\s)/g, "$1\n\n$2");
  normalized = normalized.replace(/([.:!?])\s+(-\s)/g, "$1\n\n$2");
  normalized = normalized.replace(/(\*\*)\s+(-\s)/g, "$1\n\n$2");
  return normalized;
}

export function buildAiPrompt(
  stocks: StockSnapshot[],
  totalValue: number,
  language: string
): string {
  const languageKey = language === "es" ? "es" : "en";
  const holdings = stocks
    .map((stock) => `${stock.ticker} ×${stock.shares.toFixed(4)} ($${stock.currentValue.toFixed(2)})`)
    .join(" | ");

  return `You are a cold, pragmatic, bold financial advisor with a sense of humor.
${LANGUAGE_INSTRUCTIONS[languageKey]}

Analyze a portfolio worth $${totalValue.toFixed(2)} with these holdings:
${holdings}

Format your response as clean Markdown:
- Use ## or ### for section headings (each heading on its own line, with a blank line before and after)
- Use **bold** for emphasis
- Use "- " bullet lists for lists
- Put a blank line between paragraphs
- Keep the analysis concise (under 220 words)
- Do not mention which AI model you are`;
}

export type AiInsightResult =
  | {
      ok: true;
      aiInsight: string;
      provider: string;
      modelId: string;
      usage: {
        prompt_tokens: number;
        completion_tokens: number;
        total_tokens: number;
      };
    }
  | { ok: false; status: number; error: string };

export async function runAiInsight(
  env: Env,
  modelKey: string,
  aiPrompt: string
): Promise<AiInsightResult> {
  const config = AI_MODELS[modelKey as AiModelKey];
  if (!config) {
    return { ok: false, status: 400, error: "Unknown model" };
  }

  if (modelKey === "grok") {
    if (!env.XAI_API_KEY) {
      return { ok: false, status: 503, error: "Grok API key not configured" };
    }
    const response = await fetch("https://api.x.ai/v1/chat/completions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${env.XAI_API_KEY}`,
      },
      body: JSON.stringify({
        model: config.apiModel,
        messages: [{ role: "user", content: aiPrompt }],
        max_tokens: 450,
        temperature: 0.6,
      }),
    });
    if (!response.ok) {
      const errorText = await response.text();
      return {
        ok: false,
        status: response.status,
        error: `Grok error: ${response.status} ${errorText.slice(0, 200)}`,
      };
    }
    const data = (await response.json()) as {
      choices?: Array<{ message?: { content?: string } }>;
      usage?: {
        prompt_tokens: number;
        completion_tokens: number;
        total_tokens: number;
      };
    };
    const usage = data.usage || {
      prompt_tokens: 0,
      completion_tokens: 0,
      total_tokens: 0,
    };
    return {
      ok: true,
      aiInsight: normalizeMarkdownOutput(
        data.choices?.[0]?.message?.content || "Insight generated by Grok"
      ),
      provider: config.provider,
      modelId: config.apiModel,
      usage,
    };
  }

  return { ok: false, status: 400, error: "Unknown model" };
}
